[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kernel = { path = "../kernel" }
reqwest = { version = "0.11", features = ["json", "multipart", "stream"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["full"] }
url = "2.3.1"
serde_json = "1.0"
url-escape = "0.1.1"
urlencoding = "2.1.2"
comfy-table = "6.1.4"

[dev-dependencies]
rstest = "0.16.0"